name: circular_placeholder
description: Circular Placeholder is widget. It is good to use this for circular areas when your circular designs are not ready yet.
version: 0.1.1
repository: https://github.com/levent-kantaroglu/circular_placeholder/
documentation: https://github.com/levent-kantaroglu/circular_placeholder/
funding:
  - https://www.buymeacoffee.com/kantaroglu

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
